Add command es:aliases:cat
kuzzleio/kourou pull request #164
Opened 2022-10-20 13:08 UTC by OlivierCavadenti

- Add command to list ES aliases and all associated indexes.

Close #108

2022-10-21 09:17 UTC, rolljee commented
This shell be tested with functional test

2022-10-21 09:18 UTC, rolljee requested changes
Missing functional tests

2022-10-21 14:25 UTC, Aschen approved these changes

2022-11-04 11:20 UTC, rolljee approved these changes

2022-11-04 12:17 UTC, merged