add support `--print-raw` to `sdk:query`
kuzzleio/kourou pull request #166
Opened 2022-10-28 13:24 UTC by sebtiz13

## What does this PR do?
Add flag `--print-raw` to command `sdk:query` to get only the result of query.
It's usefull to use the result of command in pipe with other CLI (like [jq](https://stedolan.github.io/jq/) for exemple)

### How should this be manually tested?

Just download this branch and try
`bin/run sdk:query index:list --print-raw`

The expected result should look like
```json
{
  "indexes": [
    "platform"
  ]
}
```

2022-10-28 14:47 UTC, Aschen approved these changes

2022-10-28 14:48 UTC, Aschen requested changes
Can you target the `1-dev` branch ?

2022-11-02 16:07 UTC, Aschen approved these changes

2022-11-03 08:54 UTC, OlivierCavadenti approved these changes

2022-11-03 09:13 UTC, merged