Support new version of logs
kuzzleio/kourou pull request #169
Opened 2022-11-23 15:47 UTC by rolljee

# Overview

> Add new logs output for the paas using the new system

* The standard output is very similar to what docker composes so that people are not too bothered by the logs

![kourou_logs](https://user-images.githubusercontent.com/10114634/203589036-ad6f6eaf-4149-4c2a-9d14-5b309cfed280.png)

2022-11-23 16:22 UTC, alexandrebouthinon approved these changes

2022-11-28 13:26 UTC, Aschen requested changes
Just a remark on the code.

Apart form that, can you please:
 - assign this PR to yourself
 - add the label

2022-12-29 21:32 UTC, Aschen approved these changes

2022-12-29 21:32 UTC, Aschen commented
@Kuruyia LGTM :+1: 

I let you merge it since I'm not sure about the release timing for this one

2022-12-30 09:29 UTC, rolljee commented
This can be merged

2022-12-30 09:29 UTC, merged