1 dev
kuzzleio/kourou pull request #173
Opened 2023-01-09 14:44 UTC by rolljee

## What does this PR do?

* app:doctor
* es:aliases:cat
* paas:logs
* scroll-ttl in index:export

### Other changes

### Boyscout

2023-01-10 14:31 UTC, rolljee commented
> Could we wait for this PR #171 ?

yea sure it is ! Any ETA on when this could be merged in this branch ?
I would like to deploy a new version of the paas that will break the paas:logs command

2023-01-11 13:09 UTC, alexandrebouthinon approved these changes

2023-01-11 15:44 UTC, Aschen requested changes
This should be done with the release tool

2023-01-11 17:59 UTC, rolljee commented
you are right

2023-01-11 17:59 UTC, closed without merging