Allow to run only Kuzzle services
kuzzleio/kourou pull request #61
Opened 2020-09-04 09:09 UTC by Aschen

## What does this PR do?

Adds the `--services-only` flag to the `instance:spawn` command to run only Kuzzle dependencies (ES & Redis)

### How should this be manually tested?

```
kourou instance:spawn --services-only
```

2020-09-09 08:37 UTC, Njuelle approved these changes

2020-09-25 09:00 UTC, scottinet approved these changes

2020-10-06 15:43 UTC, scottinet requested changes
why does this PR now add an `app:scaffold` command?

2020-10-06 15:43 UTC, scottinet commented on README.md
> +Scaffold a new Kuzzle application
```suggestion
Scaffolds a new Kuzzle application
```

2020-10-06 15:43 UTC, scottinet commented on README.md
> +  --check  Check prerequisite before running services
```suggestion
  --check  Check prerequisites before running services
```

2020-10-07 07:43 UTC, rolljee approved these changes

2020-10-07 07:47 UTC, Aschen commented
> why does this PR now add an `app:scaffold` command?

It's only the documentation, I forgot to generate the documentation in the previous PR :-1:

2020-10-07 08:14 UTC, scottinet approved these changes

2020-10-13 12:51 UTC, merged