Add option to export in JSON understandable for Kuzzle fixtures
kuzzleio/kourou pull request #82
Opened 2020-11-10 15:51 UTC by jenow

## What does this PR do?

Add option to export in JSON understandable for Kuzzle fixtures.

### How should this be manually tested?

```
kourou index:export my-index --format=raw
kourou collection:export my-index my-collection --format=raw
```

2020-11-10 16:30 UTC, Aschen requested changes
It could be interesting to have a better description of the commands, particularly to explain why choosing one or the other format (use with Kourou vs use as Kuzzle fixtures)

2020-11-10 16:35 UTC, Aschen requested changes

2020-11-10 16:35 UTC, Aschen commented on src/commands/collection/export.ts
> +      description: 'JSONL or kuzzle - kuzzle will export in Kuzzle format',
```suggestion
      description: '"jsonl" or "kuzzle" - "kuzzle" will export in Kuzzle format',
```

2020-11-10 16:35 UTC, Aschen commented on src/commands/index/export.ts
> +  static description = 'Exports an index (JSONL format or kuzzle Kuzzle format)'
```suggestion
  static description = 'Exports an index (JSONL or Kuzzle format)'
```

2020-11-10 16:35 UTC, Aschen commented on src/commands/index/export.ts
> +      description: 'JSONL or kuzzle - kuzzle will export in Kuzzle format',
```suggestion
      description: '"jsonl" or "kuzzle" - "jsonl" will export in Kourou format and "kuzzle" will export in Kuzzle fixtures format',
```

2020-11-10 16:35 UTC, Aschen commented on src/commands/index/export.ts
> +      default: 'JSONL'
```suggestion
      default: 'jsonl'
```

2020-11-10 16:35 UTC, Aschen commented on src/support/dump-collection.ts
> +export async function dumpCollectionData(sdk: any, index: string, collection: string, batchSize: number, destPath: string, query: any = {}, format = 'JSONL') {
```suggestion
export async function dumpCollectionData(sdk: any, index: string, collection: string, batchSize: number, destPath: string, query: any = {}, format = 'jsonl') {
```

2020-11-10 16:35 UTC, Aschen commented on src/support/dump-collection.ts
> +  const filename = path.join(collectionDir, (format.toUpperCase() === 'JSONL' ? 'documents.jsonl' : 'documents.json'))
```suggestion
  const filename = path.join(collectionDir, (format.toLowerCase() === 'jsonl ? 'documents.jsonl' : 'documents.json'))
```

2020-11-10 16:35 UTC, Aschen commented on src/support/dump-collection.ts
> +  if (format.toUpperCase() === 'JSONL') {
```suggestion
  if (format.toLowerCase() === 'jsonl') {
```

2020-11-10 16:35 UTC, Aschen commented on src/support/dump-collection.ts
> +export async function dumpCollectionMappings(sdk: any, index: string, collection: string, destPath: string, format = 'JSONL') {
```suggestion
export async function dumpCollectionMappings(sdk: any, index: string, collection: string, destPath: string, format = 'jsonl') {
```

2020-11-10 16:35 UTC, Aschen commented on src/support/dump-collection.ts
> +  fs.writeFileSync(filename, JSON.stringify((format.toUpperCase() === 'JSONL' ? dump : mappings), null, 2))
```suggestion
  fs.writeFileSync(filename, JSON.stringify((format.toLowerCase() === 'jsonl ? dump : mappings), null, 2))
```

2020-11-12 09:28 UTC, Aschen approved these changes

2020-11-12 09:28 UTC, Aschen commented on src/commands/index/export.ts
> +      description: '"jsonl or kuzzle - kuzzle will export in Kuzzle format usable for internal fixtures and jsonl will be usable to re import those data whith kourou',
```suggestion
      description: '"jsonl or kuzzle - kuzzle will export in Kuzzle format usable for internal fixtures and jsonl will be usable to re import those data with kourou',
```

2020-11-12 11:05 UTC, alexandrebouthinon approved these changes

2020-11-13 08:57 UTC, scottinet requested changes

2020-11-13 08:57 UTC, scottinet commented on README.md
> +                           fixtures and jsonl will be usable to re import those data whith kourou
```suggestion
                           fixtures and jsonl allows to import that data back with kourou
```

2020-11-13 08:57 UTC, scottinet commented on README.md
> +                           fixtures and jsonl will be usable to re import those data whith kourou
```suggestion
                           fixtures and jsonl allows to import that data back with kourou
```

2020-11-13 08:57 UTC, scottinet commented on src/commands/collection/export.ts
> +      description: '"jsonl or kuzzle - kuzzle will export in Kuzzle format usable for internal fixtures and jsonl will be usable to re import those data whith kourou',
```suggestion
      description: '"jsonl or kuzzle - kuzzle will export in Kuzzle format usable for internal fixtures and jsonl allows to import that data back with kourou',
```

2020-11-13 08:57 UTC, scottinet commented on src/commands/index/export.ts
> +      description: '"jsonl or kuzzle - kuzzle will export in Kuzzle format usable for internal fixtures and jsonl will be usable to re import those data with kourou',
```suggestion
      description: '"jsonl or kuzzle - kuzzle will export in Kuzzle format usable for internal fixtures and jsonl will be usable to import that data back with kourou',
```

2020-11-24 10:30 UTC, scottinet approved these changes

2020-11-24 10:31 UTC, merged