Add Nodemon
kuzzleio/kourou pull request #97
Opened 2021-02-24 13:35 UTC by Aschen

## What does this PR do?

Add missing nodemon package

2021-02-24 14:24 UTC, scottinet requested changes
Dev dependencies are only installed when you're working on the project (i.e. when you pull a git branch). So `nodemon` still won't be installed for kourou users, unless it's added to the project dependencies.

2021-02-24 16:36 UTC, Aschen commented
> Dev dependencies are only installed when you're working on the project (i.e. when you pull a git branch). So `nodemon` still won't be installed for kourou users, unless it's added to the project dependencies.

The purpose of this PR is to add `nodemon` to Kaaf dependencies when you create an app with `app:scaffold` 
Kourou users don't need `nodemon` IMHO

2021-02-24 17:34 UTC, alexandrebouthinon approved these changes

2021-02-25 09:07 UTC, scottinet commented
Dang, I didn't think straight on that one. Sorry. :expressionless:

2021-02-25 09:07 UTC, scottinet approved these changes

2021-02-25 09:07 UTC, merged